#############################################################################
# Makefile for building: pixmap.app/Contents/MacOS/pixmap
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  pixmap.pro
# Template: app
# Command: /usr/local/opt/qt/bin/qmake -o Makefile pixmap.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Weverything -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Weverything -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib
QMAKE         = /usr/local/opt/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/opt/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/opt/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pixmap1.0.0
DISTDIR = /Users/prasantapal/softwares/my/tests/pixmap/.tmp/pixmap1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.11.2/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = template.cpp
OBJECTS       = template.o
DIST          = /usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf \
		pixmap.pro template.h template.cpp
QMAKE_TARGET  = pixmap
DESTDIR       =
TARGET        = pixmap.app/Contents/MacOS/pixmap

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

$(TARGET):  $(OBJECTS)
	@test -d pixmap.app/Contents/MacOS/ || mkdir -p pixmap.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pixmap.pro /usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf \
		pixmap.pro \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile pixmap.pro
/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf:
pixmap.pro:
/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pixmap.pro

qmake_all: FORCE

pixmap.app/Contents/PkgInfo:
	@test -d pixmap.app/Contents || mkdir -p pixmap.app/Contents
	@$(DEL_FILE) pixmap.app/Contents/PkgInfo
	@echo "APPL????" > pixmap.app/Contents/PkgInfo
pixmap.app/Contents/Resources/empty.lproj:
	@test -d pixmap.app/Contents/Resources || mkdir -p pixmap.app/Contents/Resources
	@touch pixmap.app/Contents/Resources/empty.lproj

pixmap.app/Contents/Info.plist:
	@test -d pixmap.app/Contents || mkdir -p pixmap.app/Contents
	@$(DEL_FILE) pixmap.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.pixmap,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.pixmap,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,pixmap,g" -e "s,@LIBRARY@,pixmap,g" -e "s,\$${EXECUTABLE_NAME},pixmap,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/Info.plist.app >pixmap.app/Contents/Info.plist

all: Makefile \
		pixmap.app/Contents/PkgInfo \
		pixmap.app/Contents/Resources/empty.lproj \
		pixmap.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents template.h $(DISTDIR)/
	$(COPY_FILE) --parents template.cpp $(DISTDIR)/


clean: compiler_clean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean
	-$(DEL_FILE) -r pixmap.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean

####### Compile

template.o: template.cpp template.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QtCore \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qglobal.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstractanimation.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstractstate.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qabstracttransition.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qalgorithms.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qanimationgroup.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qarraydata.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qarraydataops.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qarraydatapointer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qatomic.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbasictimer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbitarray.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbuffer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbytearraylist.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcache.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qchar.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcollator.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcommandlineoption.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcommandlineparser.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcompilerdetection.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcontainerfwd.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcontiguouscache.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcoreapplication.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcoreevent.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qcryptographichash.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdeadlinetimer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdir.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdiriterator.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qeasingcurve.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qendian.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qeventloop.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qeventtransition.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qexception.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfactoryinterface.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfiledevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfileinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfileselector.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfinalstate.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qflags.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfuture.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfutureinterface.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qfuturewatcher.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qgenericatomic.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qglobalstatic.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qhash.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qhashfunctions.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qhistorystate.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qisenum.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qiterator.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qjsonarray.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qjsonvalue.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlibrary.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlibraryinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qline.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlinkedlist.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlocale.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qlockfile.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qloggingcategory.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmargins.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmath.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmetaobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmetatype.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmimedata.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmimedatabase.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmimetype.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qnamespace.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qnumeric.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qobjectdefs.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qoperatingsystemversion.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpair.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpauseanimation.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qplugin.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpluginloader.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpoint.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpointer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qprocess.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qprocessordetection.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qqueue.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qrandom.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qreadwritelock.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qrect.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qrefcount.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qregexp.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qregularexpression.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qresource.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qresultstore.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qrunnable.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsavefile.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qscopedpointer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsemaphore.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qset.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qshareddata.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsharedmemory.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsharedpointer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsignalmapper.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsignaltransition.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsocketnotifier.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstack.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstandardpaths.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstate.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstatemachine.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstorageinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringalgorithms.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringbuilder.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringlistmodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringliteral.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringmatcher.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstringview.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsysinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsystemdetection.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtemporarydir.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtextcodec.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthreadpool.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthreadstorage.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtimeline.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtimezone.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtranslator.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtypeinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtypetraits.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qurl.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qurlquery.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/quuid.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qvariantanimation.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qvarlengtharray.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qversionnumber.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qversiontagging.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qwaitcondition.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qwineventnotifier.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qxmlstream.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qtcoreversion.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QtGui \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtguiglobal.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qaccessible.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qaccessibleobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qbackingstore.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qbitmap.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qbrush.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qclipboard.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcursor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qdesktopservices.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qdrag.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qfont.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qfontdatabase.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qfontinfo.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qfontmetrics.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qgenericmatrix.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qgenericplugin.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qglyphrun.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qguiapplication.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qiconengine.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qiconengineplugin.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qimageiohandler.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qimagereader.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qimagewriter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qinputmethod.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qkeysequence.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qmatrix.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qmovie.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qoffscreensurface.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopengl.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglbuffer.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglcontext.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopengldebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopengltexture.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopengltextureblitter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopengltimerquery.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qopenglwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpagelayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpagesize.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpaintdevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpaintengine.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpainterpath.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpdfwriter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpen.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpicture.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpixelformat.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpixmapcache.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpolygon.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qquaternion.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qrasterwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qrawfont.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qregion.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qrgb.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qrgba64.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qsessionmanager.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qstatictext.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qstylehints.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qsurface.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextcursor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextdocument.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextformat.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextlist.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextobject.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtextoption.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtexttable.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtouchdevice.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtransform.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qvalidator.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qvector2d.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qvector3d.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qvector4d.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qwindowdefs.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qtguiversion.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o template.o template.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

